name: craftech-devops-grunt

on:
  push:
    paths:
      - '**.html'
    branches:
      - main

env:
  IMAGE_NAME: craftech-devops-grunt

jobs:
  docker-build-image:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s)
      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          version: latest
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
